-- vim.lsp.config('clangd', {
--     cmd = {'clangd' },
--     filetypes = {'cpp', 'h'},
-- })
--
-- vim.lsp.config('lua-language-server', {
--     cmd = { 'lua-language-server' },
--     filetypes = { 'lua' },
-- })
--
-- vim.lsp.config('rust-analyzer', {
--     cmd = { 'rust-analyzer' },
--     filetypes = { 'rs', 'toml' },
-- })
--
-- vim.lsp.enable({ 'clangd' })
-- vim.lsp.enable({ 'lua-language-server' })
-- vim.lsp.enable({'rust-analyzer'})
